[tool.poetry]
name = "rag-pathway"
version = "0.0.1"
description = ""
authors = ["Jan Chorowski <janek@pathway.com>", "Berke Can Rizai <berke@pathway.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
langchain = ">=0.0.313, <0.1"
openai = ">=1.2.4"
pathway = ">=0.7.5"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.4"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "rag_pathway"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Pathway"
integrations = ["OpenAI", "Pathway"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
